# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add_stuff": "add_stuff.ipynb",
         "say_hello": "hello_world.ipynb"}

modules = ["add.py",
           "hello.py"]

doc_url = "https://d-genk.github.io/retrofit/"

git_url = "https://github.com/d-genk/retrofit/tree/master/"

def custom_doc_links(name): return None
